### ISSUE TITLE
Stats not showing in dashboard with Wp plugin

### ISSUE THREAD

**Issue by JohnSharkey** [plausible/wordpress#139] opened 2023-06-23 11:51 UTC
Hello PA!

When I select the role for the stats to show for specific users, it doesn't work. I select "editor" and then login as one, and can't see the anaytics anywhere.  I can see it as the Admin, but not as an editor. I presume this is for it to show under Dashboard > [Analytics](/wp-admin/index.php?page=plausible_analytics_statistics). 

The only workaround where I can get it to show is to manually set the editor role to include the "manage_options" capability. The issue is that this opens up other things on the site I do not want them to do. 

Do you know of a fix for this?

Thanks,
John

**Comment by gbissland** [comment] 2023-06-23 19:51
+1 I can confirm this is not working for us either with a custom user role if it is selected to show the Dashboard.

**Comment by Dan0sz** [comment] 2023-06-27 20:38
Hey guys,

This is verified to be a bug and will be fixed in the next release.

Thanks for notifying us!

**Comment by soderlind** [comment] 2023-07-11 07:37
@Dan0sz When is the next release? I have a multisite, 115 sites with Plausible. The highest access our users get on the sites is Editor. They want their stats :)

**Comment by Dan0sz** [comment] 2023-07-12 10:49
This issue is fixed by PR https://github.com/plausible/wordpress/pull/145

**Closed by Dan0sz** 2023-07-12 10:49 UTC

**Comment by Dan0sz** [comment] 2023-07-12 10:50
@soderlind I'm sorry, due to personal circumstances I wasn't able to work on Plausible for the past few weeks (or months? -- I forgot)

But, I'm back now and I'm working on it! We'll have a new release ready soon.
